language: node_js
addons:
  sonarcloud:
    organization: "lorgiorepo-github" # the key of the org you chose at step #3
    token:
      secure: gVEbFFU/jhZu/1lQrybUeVS0uPkfONsmwfVWemaPugFddJ45H/FSygx3YJ9gzm1aVrwn7SB2QUsGe/UuTJtF9n1rL71oN4/4mZ8S4Uqkw6Tb52qIwUUsN8uA0RR6QcKliFWz/GFKvx4RXKt0XRKai/hqvnZMEMpEOS8q4PbiKVQTBV3oiLVjm0PRtaJAxX+zOvVPLrXpfz/VsNUkMlEj3OELGMx47NwxBvruwn2gEMpF/9LPRZvdrqGE6q2k1a9xZVsgjjKubDrSaCYdF3tw5JZg30tAvMW2vkZmko548zySlXUn+76D9cp+taakmH83hWiHwQi+tqRKx95/IQhjdvGfTKqrMUkj6E54RG8g/EnU04UDX8Aol+2auA8tRAD0tIm9HQzS+jKk4PfY5thYh1Z306In2vMWFX1J7ZxUg91XehDS1P1F/zJsyuPCZtXywDp+Lf2/FWPE+ob2Rwo9xHDp7tCoUPoyRIHtrXtUbAR+o5LfdA49NAV1mx1YxkSZmaWX86shzQ4cmjDnPU31u6ux5XvHjSp9oD+rD03CAfYo1ocwSRdOon9zcYEwc+fUU/xFuK5w5Lklt+NzzQHzBRrt8Li8lJRiHdC0d5/rYN6n4spE6SkFXhjNUl5l/xWxgDYqdey10KiCrJaaMTIBqTCg6bPbYIxvR3xu9gNveYY= # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: bb25dfba-03eb-4df8-8eba-61401196599c